version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5673:5672"  # RabbitMQ port for Celery broker
      - "15673:15672"  # RabbitMQ management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=rojan  # RabbitMQ default username
      - RABBITMQ_DEFAULT_PASS=rojan  # RabbitMQ default password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist RabbitMQ data

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: bank_transactions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
    ports:
      - '5432:5432'  # PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery  # Use the Celery Dockerfile
    depends_on:
      - rabbitmq  # Ensure RabbitMQ is started before Celery
      - db  # Ensure PostgreSQL is started before Celery
    volumes:
      - .:/app  # Mount your Django project directory
    environment:
      - DJANGO_SETTINGS_MODULE=proj.settings  # Set Django settings module
      - CELERY_BROKER_URL=amqp://rojan:rojan@99.209.28.83:5672// # Celery broker URL
      - CELERY_RESULT_BACKEND=db+postgresql://postgres:pwd@db:5432/bank_transactions  # Celery result backend URL

  django:
    build:
      context: .
      dockerfile: Dockerfile.django  # Use the Django Dockerfile
    ports:
      - '8000:8000'  # Django development server port
    depends_on:
      - db  # Ensure PostgreSQL is started before Django
    environment:
      - DJANGO_SETTINGS_MODULE=proj.settings  # Set Django settings module

volumes:
  rabbitmq_data:
    driver: local
  postgres_data:
    driver: local
